apiVersion: apps/v1
kind: Deployment

metadata:
  name: techstore-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: techstore

  template:
    metadata:
      labels:
        app: techstore

    spec:
      containers:
      - name: techstore-container
        image: acrnileshdev.azurecr.io/techstore:v1

        ports:
        - containerPort: 5000

        env:
        - name: PORT
          value: "5000"

        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: techstore-secret
              key: DB_HOST

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: techstore-secret
              key: DB_NAME

        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: techstore-secret
              key: DB_PORT

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: techstore-secret
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: techstore-secret
              key: DB_PASSWORD