apiVersion: v1
kind: Secret
metadata:
  name: techstore-secret
type: Opaque

stringData:
  DB_HOST: "4.240.106.119"
  DB_USER: "techuser"
  DB_PASSWORD: "Masterchief@117"
  DB_NAME: "techstoredb"
  DB_PORT: "3306"