name: Test Deployment

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd ~/test-app

            git pull origin test

            cd backend
            npm install

            cat > .env <<EOF
            DB_HOST=localhost
            DB_USER=root
            DB_PASSWORD=Masterchief@117
            DB_NAME=techstoredb
            DB_PORT=3306
            PORT=5001
            EOF

            cd ../frontend
            npm install
            npm run build

            rm -rf ../backend/dist
            cp -r dist ../backend/

            cd ../backend

            pm2 restart test-backend || pm2 start server.js --name test-backend
